format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](#e0af68)"
error_symbol = "[❯](#f7768e)"
vicmd_symbol = "[❮](#9ece6a)"

[directory]
style = "#7aa2f7"
truncation_length = 3
truncate_to_repo = false

[cmd_duration]
min_time = 1000
format = "took [$duration]($style)"
style = "#e0af68"

[git_branch]
format = "on [$branch]($style)"
style = "#bb9af7"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](red) ]($style)"
style = "#7dcfff"

[username]
style_user = "#ffb7c5" 
style_root = "#f7768e"
format = "[$user]($style)"

[hostname]
ssh_only = true
format = "@[$hostname]($style)"
style = "#ffa07a"
